// Firebase & Cloud Database Architecture for KARVIA
// Provides authenticated user sessions, Cloud Firestore operations, and safe offline fallbacks.

import AsyncStorage from '@react-native-async-storage/async-storage';

const FIREBASE_CONFIG = {
  apiKey: process.env.EXPO_PUBLIC_FIREBASE_API_KEY || 'AIzaSyMockKarviaProductionKey2026',
  authDomain: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN || 'karvia-artisan.firebaseapp.com',
  projectId: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID || 'karvia-artisan',
  storageBucket: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET || 'karvia-artisan.appspot.com',
  messagingSenderId: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '102938475612',
  appId: process.env.EXPO_PUBLIC_FIREBASE_APP_ID || '1:102938475612:android:9876543210abcdef',
};

// Seed authentic demo data for testing & offline initial state
export const INITIAL_PRODUCTS_SEED = [
  {
    id: 'prod_kanchipuram_01',
    title: 'Kanchipuram Pure Mulberry Silk Saree - Korvai Weave',
    artisanId: 'art_meena_01',
    artisanName: 'Meenakshi Sundaram',
    artisanRegion: 'Kanchipuram, Tamil Nadu',
    category: 'handloom_textiles',
    craftType: 'Kanchipuram Silk',
    craftTechnique: 'Handloom Korvai Weaving',
    material: '100% Pure Mulberry Silk & 3-Ply Gold Zari',
    colors: ['Crimson Red', 'Temple Gold Border'],
    dimensions: '6.2 Meters with Blouse Piece',
    weight: '750g',
    price: 18500,
    mrp: 24000,
    inStock: true,
    stockCount: 3,
    productionDays: 22,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&q=80',
    ],
    threeDModelUrl: 'https://cdn.karvia.crafts.org/3d/kanchipuram_saree.glb',
    tryOnSupported: true,
    arSupported: true,
    craftEvidence: {
      visualScore: 'Available',
      processProof: 'Available (Loom Warp Photo & Video)',
      materialProof: 'Silk Mark Certified (#SM-TN-49821)',
      artisanDeclaration: 'Signed declaration of pure pit loom hand weaving',
      officialCertification: 'Verified GI Tag (GI-12)',
      summary: 'Submitted evidence strongly authenticates traditional handloom Korvai process with certified gold zari.',
    },
    story: 'Woven over 22 days on a traditional four-pedal wooden pit loom by Meenakshi, a 4th-generation weaver whose family has kept the Chola-era temple border tradition alive.',
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    id: 'prod_jaipur_blue_01',
    title: 'Jaipur Blue Pottery Persian Floral Vase (14 Inch)',
    artisanId: 'art_ramesh_02',
    artisanName: 'Rameshwar Kumhar',
    artisanRegion: 'Kot Jewar, Jaipur, Rajasthan',
    category: 'pottery_ceramics',
    craftType: 'Jaipur Blue Pottery',
    craftTechnique: 'Wheel-less Low Heat Glazed Craft',
    material: 'Quartz Stone Powder, Cullet Glass, Multani Mitti, Copper Oxide',
    colors: ['Cobalt Blue', 'Turquoise', 'White Ivory'],
    dimensions: '14 x 6 x 6 Inches',
    weight: '1450g',
    price: 3400,
    mrp: 4800,
    inStock: true,
    stockCount: 8,
    productionDays: 14,
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80',
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&q=80',
    ],
    threeDModelUrl: 'https://cdn.karvia.crafts.org/3d/blue_pottery_vase.glb',
    tryOnSupported: false,
    arSupported: true, // Visualize in Space supported!
    craftEvidence: {
      visualScore: 'Available',
      processProof: 'Available (Dough preparation & Kiln firing video)',
      materialProof: 'Mineral Pigment Lab Test',
      artisanDeclaration: 'Provided by Master Artisan Rameshwar',
      officialCertification: 'Verified GI Tag (GI-31)',
      summary: 'Authentic dough composition validated. Clay-free formulation confirms true Jaipur Blue Pottery lineage.',
    },
    story: 'Unlike conventional clay pottery, this vase is hand-molded from quartz stone dough and painted using natural cobalt and copper oxide brushwork.',
    rating: 4.8,
    reviewsCount: 52,
  },
  {
    id: 'prod_dhokra_01',
    title: 'Dhokra Lost-Wax Bell Metal Nandi Figurine',
    artisanId: 'art_budhram_03',
    artisanName: 'Budhram Kashyap',
    artisanRegion: 'Bastar, Chhattisgarh',
    category: 'metal_crafts',
    craftType: 'Dhokra Brass Casting',
    craftTechnique: 'Lost-Wax (Cire Perdue) Metal Casting',
    material: 'Scrap Brass Alloy, Beeswax, Clay Matrix',
    colors: ['Antique Golden Brass', 'Earth Patina'],
    dimensions: '9 x 7 x 4 Inches',
    weight: '1800g',
    price: 4900,
    mrp: 6500,
    inStock: true,
    stockCount: 4,
    productionDays: 18,
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=800&q=80',
    ],
    threeDModelUrl: 'https://cdn.karvia.crafts.org/3d/dhokra_nandi.glb',
    tryOnSupported: false,
    arSupported: true,
    craftEvidence: {
      visualScore: 'Available',
      processProof: 'Available (Beeswax strand detailing & furnace tapping)',
      materialProof: 'Solid brass metallurgical test',
      artisanDeclaration: 'Tribal Craft Association Affidavit',
      officialCertification: 'Verified GI Tag (GI-24)',
      summary: 'Traditional lost-wax hollow core with individual hand-wound wax threads verified. Unique non-replicable piece.',
    },
    story: 'Preserving a 4,000-year-old metallurgical lineage dating back to Mohenjo-daro Dancing Girl. Each mould is shattered upon firing, rendering each sculpture unique.',
    rating: 5.0,
    reviewsCount: 29,
  },
  {
    id: 'prod_madhubani_01',
    title: 'Madhubani Kohbar Tree of Life Handpainted Canvas',
    artisanId: 'art_sunita_04',
    artisanName: 'Sunita Devi',
    artisanRegion: 'Madhubani, Bihar',
    category: 'folk_paintings',
    craftType: 'Madhubani Art',
    craftTechnique: 'Bamboo Nib & Twig Painting (Bharni Style)',
    material: 'Handmade Khadi Paper Canvas, Natural Plant Dyes (Turmeric, Lampblack, Indigo)',
    colors: ['Ochre', 'Deep Terracotta', 'Indigo', 'Forest Green'],
    dimensions: '24 x 18 Inches (Framed)',
    weight: '1200g',
    price: 6200,
    mrp: 8500,
    inStock: true,
    stockCount: 2,
    productionDays: 16,
    images: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80',
    ],
    threeDModelUrl: 'https://cdn.karvia.crafts.org/3d/madhubani_frame.glb',
    tryOnSupported: false,
    arSupported: true,
    craftEvidence: {
      visualScore: 'Available',
      processProof: 'Available (Natural pigment extraction & line work)',
      materialProof: 'Plant-based botanical dye test',
      artisanDeclaration: 'Self-declaration by State Awardee Sunita Devi',
      officialCertification: 'Verified GI Tag (GI-11)',
      summary: 'Hand-drawn fine double-line work with plant-derived non-chemical pigments verified.',
    },
    story: 'Handcrafted using bamboo nibs without preliminary pencil sketching. Celebrates the sacred Kohbar fertility motif and the harmonious flora and fauna of Mithila.',
    rating: 4.9,
    reviewsCount: 44,
  },
  {
    id: 'prod_bandhani_01',
    title: 'Kutch Bandhani Pure Georgette Dupatta with Gota Patti',
    artisanId: 'art_fatima_05',
    artisanName: 'Fatima Khatun',
    artisanRegion: 'Bhuj, Kutch, Gujarat',
    category: 'handloom_textiles',
    craftType: 'Bandhani Tie & Dye',
    craftTechnique: 'Fine Fingernail Knotting (Ekdali & Shikari)',
    material: 'Pure Viscose Georgette, Fast Natural Dyes, Gold Ribbon',
    colors: ['Rust Terracotta', 'Mustard Yellow', 'Deep Forest'],
    dimensions: '2.5 x 1 Meters',
    weight: '380g',
    price: 4200,
    mrp: 5800,
    inStock: true,
    stockCount: 7,
    productionDays: 12,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80',
    ],
    threeDModelUrl: 'https://cdn.karvia.crafts.org/3d/bandhani_dupatta.glb',
    tryOnSupported: true, // Garment Try-On Supported!
    arSupported: false,
    craftEvidence: {
      visualScore: 'Available',
      processProof: 'Available (Tied resist knots photo before dye immersion)',
      materialProof: 'Dye fastness lab report',
      artisanDeclaration: 'Kutch Weavers Welfare Society Verification',
      officialCertification: 'Verified GI Tag (GI-38)',
      summary: 'Over 8,000 individually hand-tied knots counted per piece before vegetable dye bath.',
    },
    story: 'Crafted in rural Kutch where women artisans tie microscopic cotton threads around tiny pinch folds of fabric before multi-stage dip immersion dyeing.',
    rating: 4.7,
    reviewsCount: 31,
  }
];

export default {
  FIREBASE_CONFIG,
  INITIAL_PRODUCTS_SEED,
};
