// Guru–Shishya / Living Craft Archive Data
// Preserving tacit craft knowledge, master-apprentice lineages, and oral histories.

export const HERITAGE_ARCHIVES = [
  {
    id: 'archive_kanchipuram_korvai',
    craftName: 'Kanchipuram Silk Handloom Weaving',
    tradition: 'Chola Dynasty Temple Border Korvai Petni',
    region: 'Kanchipuram, Tamil Nadu',
    giTag: 'GI-12',
    masterArtisan: {
      name: 'Guru Meenakshi Sundaram',
      title: 'Master Weaver & Lineage Custodian',
      experience: '42 years of pit-loom weaving',
      avatarEmoji: '👵🏽',
      honors: 'National Merit Certificate, Tamil Nadu State Kalaimamani Nominee',
      lineage: '4th Generation weaver of the Sundaram lineage of Pillayar Palayam',
      quote: 'The loom is not merely a machine; it is our sacred altar. The three-shuttle Korvai cannot be taught through diagrams—it lives in the rhythm of the foot-pedal and the heartbeat of the weaver.',
    },
    apprentice: {
      name: 'Priya Sundaram',
      relationship: 'Daughter & 5th-Generation Apprentice',
      yearsLearning: '6 years under direct tutelage',
      specialization: 'Border warp locking & temple spire (Mullum Murrum) motifs',
      quote: 'Amma taught me to listen to the wooden reed. When the tension is true, the silk sings a distinct note.',
    },
    tacitTechniques: [
      {
        step: 1,
        title: 'Three-Shuttle Petni Interlocking (Korvai)',
        description: 'Requires two weavers working simultaneously or a master weaver managing two separate side shuttles for borders and one central shuttle for the saree body. The warp threads of different colors are interlocked with microscopic finger twists before beating.',
        preservationStatus: 'Critically Endangered (High manual fatigue, non-mechanizable)',
        videoUrl: 'https://cdn.karvia.crafts.org/heritage/korvai_warp_lock.mp4',
        keyTip: 'The warp knotting must happen in the fraction of a second when the shedding pedal is fully depressed.',
      },
      {
        step: 2,
        title: 'Adai Card Weft Selection for Temple Gopuram Motifs',
        description: 'Before modern jacquards, the Adai—a system of hand-knotted cotton cords suspended above the pit loom—was manipulated by the apprentice to lift individual warp ends creating the sacred triangular temple spires.',
        preservationStatus: 'Preserved within 8 family looms in Kanchipuram',
        keyTip: 'Never rush the Adai string tension during monsoon humidity; silk absorbs ambient moisture.',
      },
      {
        step: 3,
        title: 'Three-Ply Pure Gold Zari Calibration',
        description: 'Genuine silver wire electroplated with 24-karat gold wound around a pure silk core yarn. The master tests authenticity by testing ductility and burning a single thread to observe clean ash without synthetic chemical residue.',
        preservationStatus: 'Living Practice with BIS Silk Mark certification',
        keyTip: 'Pure zari reflects soft amber warmth; synthetic lurex produces a harsh white glare.',
      },
    ],
    oralHistory: {
      title: 'Oral History: How Our Ancestors Weaved for the Chola Temples',
      recordedDate: '2026-04-12',
      duration: '4 min 18 sec',
      audioTranscript: 'In my grandfather’s time, we wove only for the Varadaraja Perumal temple festivals. The red dye came from madder roots brought from the Coromandel coast, and the gold came from temple bullion. We never sold our work in open markets; every saree was dedicated to the deity or royal patrons. Today, with KARVIA, our craft reaches patrons who value the prayer woven into every thread.',
      languages: ['Tamil', 'English Translation'],
    },
  },
  {
    id: 'archive_bastar_dhokra',
    craftName: 'Dhokra Lost-Wax Bell Metal Casting',
    tradition: '4,000-Year-Old Harappan Cire Perdue Metal Craft',
    region: 'Bastar, Chhattisgarh',
    giTag: 'GI-24',
    masterArtisan: {
      name: 'Guru Budhram Kashyap',
      title: 'Tribal Master Sculptor',
      experience: '38 years of furnace tapping & beeswax sculpting',
      avatarEmoji: '👴🏾',
      honors: 'Shilp Guru Award Nominee, Bastar Crafts Guild Elder',
      lineage: 'Ghadwa Tribal Community of Kondagaon',
      quote: 'Every sculpture requires breaking the clay womb. The mother clay must crack so the bronze spirit can breathe.',
    },
    apprentice: {
      name: 'Ramu Kashyap',
      relationship: 'Nephew & Apprentice',
      yearsLearning: '8 years',
      specialization: 'Beeswax thread extrusion & underground pit furnace firing',
      quote: 'Learning to judge metal temperature simply by the orange flame color from the furnace chimney took me five years.',
    },
    tacitTechniques: [
      {
        step: 1,
        title: 'Natural Beeswax Thread (Dhokra) Extrusion',
        description: 'Artisans blend pure forest beeswax with damar gum (Ral) from Sal trees. The pliable wax is hand-rolled or pressed through a wooden piston die to create uniform 1mm strands that are wound in concentric spirals over a sun-dried clay core.',
        preservationStatus: 'Vulnerable to industrial paraffin substitutes',
        keyTip: 'Warm the wax ball only using gentle palm heat; charcoal flame will make it brittle.',
      },
      {
        step: 2,
        title: 'Double-Layered Riverbed Clay Matrix',
        description: 'The wax model is coated with a slurry of fine riverbed silt mixed with cow dung and rice husk. The organic fibers burn away during heating, creating porous micro-vents that allow trapped gases to escape without shattering the mould.',
        preservationStatus: 'Living Ancestral Technique',
        keyTip: 'The clay must cure in shade for 7 days; sun drying causes hairline fissures that leak molten metal.',
      },
      {
        step: 3,
        title: 'Pit Furnace Charging & Crucible Inversion',
        description: 'Scrap bell metal and brass are sealed in a clay crucible placed atop the mould. When the brass reaches 1,050°C, the master rapidly inverts the red-hot crucible using hand-forged tongs so the liquid bronze rushes into the hollow vacated by melted wax.',
        preservationStatus: 'Mastery Required (Dangerous and high precision)',
        keyTip: 'Listen for the liquid metal hiss; a dull thud indicates molten metal has cooled prematurely.',
      },
    ],
    oralHistory: {
      title: 'Oral History: The Legend of the Dancing Girl and the Forest Spirits',
      recordedDate: '2026-06-20',
      duration: '5 min 02 sec',
      audioTranscript: 'Our elders tell us that when the world was young, the metal spoke to the forest dwellers. We never sketch our figures on paper. Before we roll the first wax strand, we offer mahua flowers to the earth. The Nandi, the deer, the village musician—they are not ornaments; they are our ancestors watching over the forest.',
      languages: ['Halbi', 'Hindi', 'English Translation'],
    },
  },
  {
    id: 'archive_jaipur_blue_pottery',
    craftName: 'Jaipur Low-Heat Glazed Blue Pottery',
    tradition: 'Persian-Mughal Wheel-less Quartz Ceramic',
    region: 'Kot Jewar, Jaipur, Rajasthan',
    giTag: 'GI-31',
    masterArtisan: {
      name: 'Guru Rameshwar Kumhar',
      title: 'National Master Potter',
      experience: '35 years of low-fire quartz formulation',
      avatarEmoji: '🧔🏽',
      honors: 'Presidential Handicrafts Award Winner',
      lineage: 'Direct disciple of Padmashri Kripal Singh Shekhawat',
      quote: 'We are the only potters who do not use clay from the river. Our vessel is born from stone, glass, and desert earth.',
    },
    apprentice: {
      name: 'Kavita Kumhar',
      relationship: 'Daughter & Master Painter',
      yearsLearning: '7 years',
      specialization: 'Natural cobalt oxide brushwork & Persian arabesque motifs',
      quote: 'Painting on raw quartz dough is like painting on sugar—one wrong brushstroke absorbs immediately and cannot be erased.',
    },
    tacitTechniques: [
      {
        step: 1,
        title: 'Clay-Free Quartz Dough Preparation',
        description: 'Made by grinding quartz stone powder, cullet glass (recycled bottle glass), Multani Mitti (Fullers Earth), gum (Gond), and natural water. The dough is rolled flat with wooden rolling pins and pressed into open plaster moulds without a potters wheel.',
        preservationStatus: 'Endangered due to chemical ceramic alternatives',
        keyTip: 'The cullet glass must be sieved through fine muslin; coarse particles cause thermal shock cracks.',
      },
      {
        step: 2,
        title: 'Natural Mineral Oxide Freehand Painting',
        description: 'Brushes crafted from squirrel hair apply cobalt oxide (for deep sapphire blue) and copper oxide (for vibrant turquoise green) directly onto the porous unglazed vessel.',
        preservationStatus: 'High Artistic Significance',
        keyTip: 'Cobalt oxide appears dull gray before firing; the painter must hold the finished fired blue in their mind.',
      },
    ],
    oralHistory: {
      title: 'Oral History: Bringing the Turquoise Glaze from Samarkand to Jaipur',
      recordedDate: '2026-07-04',
      duration: '3 min 45 sec',
      audioTranscript: 'Maharaja Sawai Ram Singh saw kite flyers whose strings were coated with blue glass powder that outshone the sun. He sent our ancestors to Delhi to master this Persian glaze. For generations, we guarded the kiln temperature secret. Today, KARVIA allows us to teach young apprentices while selling directly to patrons worldwide.',
      languages: ['Rajasthani', 'Hindi', 'English Translation'],
    },
  },
];

export default HERITAGE_ARCHIVES;
