// 13 Official Indian Languages Configuration for KARVIA
export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'Pan-India', rtl: false },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu', rtl: false },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North/Central India', rtl: false },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala', rtl: false },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh & Telangana', rtl: false },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka', rtl: false },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab', rtl: false },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal', rtl: false },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra', rtl: false },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat', rtl: false },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha', rtl: false },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam & NE', rtl: false },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'Pan-India', rtl: true },
];

export const translations = {
  en: {
    appName: 'KARVIA',
    tagline: 'Craft. Culture. Connected.',
    roleArtisan: 'Artisan',
    roleBuyer: 'Buyer',
    roleAdmin: 'Admin',
    welcomeBack: 'Welcome back',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    searchPlaceholder: 'Search authentic crafts, artisans, regions...',
    addMyCraft: 'Add New Craft',
    voiceAssistant: 'KARVIA Voice AI',
    voicePrompt: 'Tap microphone and speak in your language...',
    tellKarvia: 'Tell KARVIA what you need...',
    smartCatalog: 'AI Smart Catalog',
    craftEvidence: 'Craft Evidence Profile',
    fairPricing: 'Fair Price Assistant',
    trendFusion: 'Trend Fusion Studio',
    rawMaterial: 'Raw Material Intelligence',
    schemes: 'Government Schemes',
    myProducts: 'My Products',
    activeOrders: 'Active Orders',
    totalEarnings: 'Total Earnings',
    marketOpportunities: 'Market Opportunities',
    viewIn3D: 'View in 3D',
    virtualTryOn: 'Virtual Try-On',
    visualizeInSpace: 'Visualize in My Space',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    checkout: 'Proceed to Checkout',
    orderTracking: 'Track Order',
    reviews: 'Artisan Reviews',
    verifiedArtisan: 'Verified Craftsperson',
    handcrafted: '100% Handcrafted',
    offlineNotice: 'You are working offline. Edits will synchronize automatically.',
    syncPending: 'Syncing your updates...',
    synced: 'All changes saved to cloud',
    saveDraft: 'Save Draft',
    publishProduct: 'Publish to Marketplace',
    priceBreakdown: 'Price Breakdown',
    materialsCost: 'Raw Materials Cost',
    labourTime: 'Labour & Crafting Time',
    suggestedPrice: 'Suggested Selling Price',
    orders: 'Orders',
    insights: 'Insights',
    profile: 'Profile',
    explore: 'Explore',
    cart: 'Cart',
    wishlist: 'Wishlist',
    filter: 'Filter',
    allCrafts: 'All Crafts',
    selectLanguage: 'Choose Your Preferred Language',
    continue: 'Continue',
    skip: 'Skip',
    getStarted: 'Get Started',
  },

  ta: {
    appName: 'கார்வியா',
    tagline: 'கைவினை. கலாச்சாரம். இணைப்பு.',
    roleArtisan: 'கைவினைஞர்',
    roleBuyer: 'வாங்குபவர்',
    roleAdmin: 'நிர்வாகி',
    welcomeBack: 'மீண்டும் நல்வரவு',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    searchPlaceholder: 'கைவினைப் பொருட்கள், கலைஞர்களைத் தேடுங்கள்...',
    addMyCraft: 'புதிய கைவினைப் பொருள் சேர்க்க',
    voiceAssistant: 'கார்வியா குரல் AI',
    voicePrompt: 'மைக்ரோஃபோனைத் தொட்டு உங்கள் மொழியில் பேசுங்கள்...',
    tellKarvia: 'உங்களுக்கு என்ன தேவை என்பதை கார்வியாவிடம் கூறுங்கள்...',
    smartCatalog: 'AI ஸ்மார்ட் பட்டியல்',
    craftEvidence: 'கைவினை சான்றளிப்பு சுயவிவரம்',
    fairPricing: 'நியாய விலை உதவியாளர்',
    trendFusion: 'சந்தை போக்கு ஒருங்கிணைப்பு',
    rawMaterial: 'மூலப்பொருள் தேவை நுண்ணறிவு',
    schemes: 'அரசு நலத்திட்டங்கள்',
    myProducts: 'எனது தயாரிப்புகள்',
    activeOrders: 'செயலில் உள்ள ஆர்டர்கள்',
    totalEarnings: 'மொத்த வருவாய்',
    marketOpportunities: 'சந்தை வாய்ப்புகள்',
    viewIn3D: '3D இல் காண்க',
    virtualTryOn: 'மெய்நிகர் ஆடை முயற்சி',
    visualizeInSpace: 'உங்கள் இடத்தில் வைத்துப் பாருங்கள்',
    addToCart: 'கூடையில் சேர்',
    buyNow: 'உடனே வாங்கு',
    checkout: 'பணம் செலுத்த தொடரவும்',
    orderTracking: 'ஆர்டரைக் கண்காணிக்கவும்',
    reviews: 'மதிப்புரைகள்',
    verifiedArtisan: 'சரிபார்க்கப்பட்ட கைவினைஞர்',
    handcrafted: '100% கைவினைப் பொருள்',
    offlineNotice: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். தானாகவே ஒத்திசைக்கப்படும்.',
    syncPending: 'ஒத்திசைக்கப்படுகிறது...',
    synced: 'அனைத்து மாற்றங்களும் சேமிக்கப்பட்டன',
    saveDraft: 'வரைவாக சேமிக்க',
    publishProduct: 'சந்தையில் வெளியிடவும்',
    priceBreakdown: 'விலை விவரம்',
    materialsCost: 'மூலப்பொருள் செலவு',
    labourTime: 'உழைப்பு & கைவினை நேரம்',
    suggestedPrice: 'பரிந்துரைக்கப்பட்ட விற்பனை விலை',
    orders: 'ஆர்டர்கள்',
    insights: 'நுண்ணறிவு',
    profile: 'சுயவிவரம்',
    explore: 'ஆராய்க',
    cart: 'கூடை',
    wishlist: 'விருப்பப் பட்டியல்',
    filter: 'வடிகட்டி',
    allCrafts: 'அனைத்து கைவினைகள்',
    selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    continue: 'தொடரவும்',
    skip: 'தவிர்க்க',
    getStarted: 'தொடங்குங்கள்',
  },

  hi: {
    appName: 'कार्विया',
    tagline: 'शिल्प। संस्कृति। संपर्क।',
    roleArtisan: 'शिल्पकार',
    roleBuyer: 'खरीदार',
    roleAdmin: 'प्रशासक',
    welcomeBack: 'वापसी पर स्वागत है',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    searchPlaceholder: 'पारंपरिक शिल्प, कारीगर, क्षेत्र खोजें...',
    addMyCraft: 'नया उत्पाद जोड़ें',
    voiceAssistant: 'कार्विया वॉयस AI',
    voicePrompt: 'माइक दबाएं और अपनी भाषा में बोलें...',
    tellKarvia: 'कार्विया को बताएं कि आपको क्या चाहिए...',
    smartCatalog: 'AI स्मार्ट कैटलॉग',
    craftEvidence: 'शिल्प प्रमाण प्रोफाइल',
    fairPricing: 'उचित मूल्य सहायक',
    trendFusion: 'ट्रेंड फ्यूजन स्टूडियो',
    rawMaterial: 'कच्चा माल मांग विश्लेषण',
    schemes: 'सरकारी योजनाएं',
    myProducts: 'मेरे उत्पाद',
    activeOrders: 'सक्रिय ऑर्डर',
    totalEarnings: 'कुल कमाई',
    marketOpportunities: 'बाजार के अवसर',
    viewIn3D: '3D में देखें',
    virtualTryOn: 'वर्चुअल ट्राई-ऑन',
    visualizeInSpace: 'अपने स्थान में देखें',
    addToCart: 'कार्ट में जोड़ें',
    buyNow: 'अभी खरीदें',
    checkout: 'चेकआउट करें',
    orderTracking: 'ऑर्डर ट्रैक करें',
    reviews: 'समीक्षाएं',
    verifiedArtisan: 'प्रमाणित शिल्पकार',
    handcrafted: '100% हस्तनिर्मित',
    offlineNotice: 'आप ऑफलाइन काम कर रहे हैं। बदलाव अपने आप सिंक होंगे।',
    syncPending: 'सिंक हो रहा है...',
    synced: 'सभी बदलाव सुरक्षित हैं',
    saveDraft: 'ड्राफ्ट सहेजें',
    publishProduct: 'मार्केटप्लेस में प्रकाशित करें',
    priceBreakdown: 'मूल्य विवरण',
    materialsCost: 'कच्चा माल लागत',
    labourTime: 'मेहनत और शिल्प समय',
    suggestedPrice: 'सुझाया गया विक्रय मूल्य',
    orders: 'ऑर्डर',
    insights: 'जानकारी',
    profile: 'प्रोफाइल',
    explore: 'खोजें',
    cart: 'कार्ट',
    wishlist: 'इच्छा सूची',
    filter: 'फ़िल्टर',
    allCrafts: 'सभी शिल्प',
    selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
    continue: 'जारी रखें',
    skip: 'छोड़ें',
    getStarted: 'शुरू करें',
  },

  ml: {
    appName: 'കാർവിയ',
    tagline: 'കരകൗശലം. സംസ്കാരം. കണക്റ്റഡ്.',
    roleArtisan: 'കരകൗശല വിദഗ്ധൻ',
    roleBuyer: 'വാങ്ങുന്നയാൾ',
    roleAdmin: 'അഡ്മിൻ',
    welcomeBack: 'സ്വാഗതം',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ചതിരിഞ്ഞ്',
    goodEvening: 'ശുഭ സായാഹ്നം',
    searchPlaceholder: 'കരകൗശല വസ്തുക്കൾ തിരയുക...',
    addMyCraft: 'പുതിയ ഉൽപ്പന്നം ചേർക്കുക',
    voiceAssistant: 'കാർവിയ വോയ്സ് AI',
    voicePrompt: 'മൈക്ക് ടാപ്പ് ചെയ്ത് നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക...',
    tellKarvia: 'നിങ്ങൾക്ക് എന്താണ് വേണ്ടതെന്ന് കാർവിയയോട് പറയുക...',
    smartCatalog: 'AI സ്മാർട്ട് കാറ്റലോഗ്',
    craftEvidence: 'കരകൗശല തെളിവ് പ്രൊഫൈൽ',
    fairPricing: 'ന്യായവില സഹായി',
    trendFusion: 'ട്രെൻഡ് ഫ്യൂഷൻ',
    rawMaterial: 'അസംസ്കൃത വസ്തുക്കളുടെ വിവരങ്ങൾ',
    schemes: 'സർക്കാർ പദ്ധതികൾ',
    myProducts: 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
    activeOrders: 'ഓർഡറുകൾ',
    totalEarnings: 'ആകെ വരുമാനം',
    marketOpportunities: 'വിപണി സാധ്യതകൾ',
    viewIn3D: '3D യിൽ കാണുക',
    virtualTryOn: 'വെർച്വൽ ട്രൈ-ഓൺ',
    visualizeInSpace: 'നിങ്ങളുടെ സ്ഥലത്ത് വച്ചുനോക്കുക',
    addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    buyNow: 'ഇപ്പോൾ വാങ്ങുക',
    checkout: 'ചെക്ക്ഔട്ട് ചെയ്യുക',
    orderTracking: 'ട്രാക്ക് ഓർഡർ',
    reviews: 'അവലോകനങ്ങൾ',
    verifiedArtisan: 'പരിശോധിച്ച ശില്പി',
    handcrafted: '100% കൈകൊണ്ട് നിർമ്മിച്ചത്',
    offlineNotice: 'നിങ്ങൾ ഓഫ്‌ലൈനിലാണ്. തനിയെ സിങ്ക് ചെയ്യും.',
    syncPending: 'സിങ്കിംഗ്...',
    synced: 'എല്ലാം സേവ് ചെയ്തു',
    saveDraft: 'ഡ്രാഫ്റ്റ് സേവ് ചെയ്യുക',
    publishProduct: 'പബ്ലിഷ് ചെയ്യുക',
    priceBreakdown: 'വില വിവരണം',
    materialsCost: 'മെറ്റീരിയൽ ചിലവ്',
    labourTime: 'തൊഴിൽ സമയം',
    suggestedPrice: 'നിർദ്ദേശിച്ച വിൽപന വില',
    orders: 'ഓർഡറുകൾ',
    insights: 'വിവരങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    explore: 'പര്യവേക്ഷണം',
    cart: 'കാർട്ട്',
    wishlist: 'ആഗ്രഹപ്പട്ടിക',
    filter: 'ഫിൽട്ടർ',
    allCrafts: 'എല്ലാ കരകൗശലങ്ങളും',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    continue: 'തുടരുക',
    skip: 'ഒഴിവാക്കുക',
    getStarted: 'ആരംഭിക്കുക',
  },

  te: {
    appName: 'కార్వియా',
    tagline: 'చేతిపని. సంస్కృతి. అనుసంధానం.',
    roleArtisan: 'చేతివృత్తిదారుడు',
    roleBuyer: 'కొనుగోలుదారు',
    roleAdmin: 'అడ్మిన్',
    welcomeBack: 'పునఃస్వాగతం',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    searchPlaceholder: 'చేతిపనులు, కళాకారులను శోధించండి...',
    addMyCraft: 'కొత్త ఉత్పత్తిని జోడించండి',
    voiceAssistant: 'కార్వియా వాయిస్ AI',
    voicePrompt: 'మైక్ నొక్కి మీ భాషలో మాట్లాడండి...',
    tellKarvia: 'మీకు ఏమి కావాలో కార్వియాకు చెప్పండి...',
    smartCatalog: 'AI స్మార్ట్ కేటలాగ్',
    craftEvidence: 'చేతిపని సాక్ష్యాల ప్రొఫైల్',
    fairPricing: 'సహేతుక ధర సహాయకుడు',
    trendFusion: 'ట్రెండ్ ఫ్యూజన్ స్టూడియో',
    rawMaterial: 'ముడిసరుకు డిమాండ్ సమాచారం',
    schemes: 'ప్రభుత్వ పథకాలు',
    myProducts: 'నా ఉత్పత్తులు',
    activeOrders: 'యాక్టివ్ ఆర్డర్లు',
    totalEarnings: 'మొత్తం సంపాదన',
    marketOpportunities: 'మార్కెట్ అవకాశాలు',
    viewIn3D: '3D లో చూడండి',
    virtualTryOn: 'వర్చువల్ ట్రై-ఆన్',
    visualizeInSpace: 'మీ ప్రదేశంలో ఉంచి చూడండి',
    addToCart: 'కార్ట్‌కు జోడించండి',
    buyNow: 'ఇప్పుడే కొనండి',
    checkout: 'చెల్లింపుకు వెళ్లండి',
    orderTracking: 'ఆర్డర్ ట్రాకింగ్',
    reviews: 'సమీక్షలు',
    verifiedArtisan: 'ధృవీకరించబడిన కళాకారుడు',
    handcrafted: '100% చేతితో తయారు చేయబడినది',
    offlineNotice: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. ఆటోమేటిక్‌గా సింక్ అవుతుంది.',
    syncPending: 'సింక్ అవుతోంది...',
    synced: 'మార్పులు సేవ్ అయ్యాయి',
    saveDraft: 'డ్రాఫ్ట్ సేవ్ చేయండి',
    publishProduct: 'మార్కెట్‌లో ప్రచురించండి',
    priceBreakdown: 'ధర వివరాలు',
    materialsCost: 'ముడిసరుకు ఖర్చు',
    labourTime: 'శ్రమ & చేతిపని సమయం',
    suggestedPrice: 'సూచించిన అమ్మకపు ధర',
    orders: 'ఆర్డర్లు',
    insights: 'అవగాహన',
    profile: 'ప్రొఫైల్',
    explore: 'అన్వేషించండి',
    cart: 'కార్ట్',
    wishlist: 'కోరికల జాబితా',
    filter: 'ఫిల్టర్',
    allCrafts: 'అన్ని కళారూపాలు',
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    continue: 'కొనసాగించండి',
    skip: 'దాటవేయి',
    getStarted: 'ప్రారంభించండి',
  },

  kn: {
    appName: 'ಕಾರ್ವಿಯಾ',
    tagline: 'ಕರಕುಶಲತೆ. ಸಂಸ್ಕೃತಿ. ಸಂಪರ್ಕ.',
    roleArtisan: 'ಕುಶಲಕರ್ಮಿ',
    roleBuyer: 'ಖರೀದಿದಾರ',
    roleAdmin: 'ನಿರ್ವಾಹಕ',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    searchPlaceholder: 'ಕರಕುಶಲ ವಸ್ತುಗಳು, ಕುಶಲಕರ್ಮಿಗಳನ್ನು ಹುಡುಕಿ...',
    addMyCraft: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    voiceAssistant: 'ಕಾರ್ವಿಯಾ ವಾಯ್ಸ್ AI',
    voicePrompt: 'ಮೈಕ್ ಒತ್ತಿ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ...',
    tellKarvia: 'ನಿಮಗೆ ಏನು ಬೇಕು ಎಂದು ಕಾರ್ವಿಯಾಗೆ ತಿಳಿಸಿ...',
    smartCatalog: 'AI ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಟಲಾಗ್',
    craftEvidence: 'ಕರಕುಶಲ ಪುರಾವೆ ಪ್ರೊಫೈಲ್',
    fairPricing: 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಸಹಾಯಕ',
    trendFusion: 'ಟ್ರೆಂಡ್ ಫ್ಯೂಷನ್ ಸ್ಟುಡಿಯೋ',
    rawMaterial: 'ಕಚ್ಚಾ ವಸ್ತುಗಳ ಮಾಹಿತಿ',
    schemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    myProducts: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    activeOrders: 'ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳು',
    totalEarnings: 'ಒಟ್ಟು ಗಳಿಕೆ',
    marketOpportunities: 'ಮಾರುಕಟ್ಟೆ ಅವಕಾಶಗಳು',
    viewIn3D: '3D ಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    virtualTryOn: 'ವರ್ಚುವಲ್ ಟ್ರೈ-ಆನ್',
    visualizeInSpace: 'ನಿಮ್ಮ ಜಾಗದಲ್ಲಿರಿಸಿ ನೋಡಿ',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    buyNow: 'ಈಗಲೇ ಖರೀದಿಸಿ',
    checkout: 'ಚೆಕ್‌ಔಟ್ ಮುಂದುವರಿಸಿ',
    orderTracking: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    verifiedArtisan: 'ದೃಢೀಕೃತ ಕುಶಲಕರ್ಮಿ',
    handcrafted: '100% ಕೈಯಿಂದ ಮಾಡಲ್ಪಟ್ಟಿದೆ',
    offlineNotice: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ. ಬದಲಾವಣೆಗಳು ಸ್ವಯಂ ಸಿಂಕ್ ಆಗುತ್ತವೆ.',
    syncPending: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    synced: 'ಎಲ್ಲ ಬದಲಾವಣೆಗಳು ಉಳಿದಿವೆ',
    saveDraft: 'ಡ್ರಾಫ್ಟ್ ಉಳಿಸಿ',
    publishProduct: 'ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಪ್ರಕಟಿಸಿ',
    priceBreakdown: 'ಬೆಲೆ ವಿವರ',
    materialsCost: 'ಕಚ್ಚಾ ವಸ್ತುಗಳ ವೆಚ್ಚ',
    labourTime: 'ಶ್ರಮ ಮತ್ತು ಕುಶಲತೆಯ ಸಮಯ',
    suggestedPrice: 'ಸೂಚಿಸಲಾದ ಮಾರಾಟ ಬೆಲೆ',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    insights: 'ಮಾಹಿತಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    explore: 'ಅನ್ವೇಷಿಸಿ',
    cart: 'ಕಾರ್ಟ್',
    wishlist: 'ಮೆಚ್ಚಿನ ಪಟ್ಟಿ',
    filter: 'ಫಿಲ್ಟರ್',
    allCrafts: 'ಎಲ್ಲ ಕರಕುಶಲಗಳು',
    selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    continue: 'ಮುಂದುವರಿಸಿ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
  },

  pa: {
    appName: 'ਕਾਰਵੀਆ',
    tagline: 'ਦਸਤਕਾਰੀ। ਸੱਭਿਆਚਾਰ। ਜੁੜਿਆ ਹੋਇਆ।',
    roleArtisan: 'ਕਾਰੀਗਰ',
    roleBuyer: 'ਖਰੀਦਦਾਰ',
    roleAdmin: 'ਐਡਮਿਨ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    goodAfternoon: 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
    goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
    searchPlaceholder: 'ਦਸਤਕਾਰੀ, ਕਾਰੀਗਰਾਂ ਦੀ ਖੋਜ ਕਰੋ...',
    addMyCraft: 'ਨਵਾਂ ਉਤਪਾਦ ਜੋੜੋ',
    voiceAssistant: 'ਕਾਰਵੀਆ ਵੌਇਸ AI',
    voicePrompt: 'ਮਾਈਕ ਦਬਾਓ ਅਤੇ ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਬੋਲੋ...',
    tellKarvia: 'ਕਾਰਵੀਆ ਨੂੰ ਦੱਸੋ ਕਿ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ...',
    smartCatalog: 'AI ਸਮਾਰਟ ਕੈਟਾਲਾਗ',
    craftEvidence: 'ਦਸਤਕਾਰੀ ਸਬੂਤ ਪ੍ਰੋਫਾਈਲ',
    fairPricing: 'ਵਾਜਬ ਕੀਮਤ ਸਹਾਇਕ',
    trendFusion: 'ਟਰੈਂਡ ਫਿਊਜ਼ਨ ਸਟੂਡੀਓ',
    rawMaterial: 'ਕੱਚੇ ਮਾਲ ਦੀ ਮੰਗ ਦੀ ਜਾਣਕਾਰੀ',
    schemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    myProducts: 'ਮੇਰੇ ਉਤਪਾਦ',
    activeOrders: 'ਸਰਗਰਮ ਆਰਡਰ',
    totalEarnings: 'ਕੁੱਲ ਕਮਾਈ',
    marketOpportunities: 'ਮਾਰਕੀਟ ਮੌਕੇ',
    viewIn3D: '3D ਵਿੱਚ ਦੇਖੋ',
    virtualTryOn: 'ਵਰਚੁਅਲ ਟਰਾਈ-ਆਨ',
    visualizeInSpace: 'ਆਪਣੀ ਜਗ੍ਹਾ ਵਿੱਚ ਰੱਖ ਕੇ ਦੇਖੋ',
    addToCart: 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    buyNow: 'ਹੁਣੇ ਖਰੀਦੋ',
    checkout: 'ਚੈੱਕਆਉਟ ਕਰੋ',
    orderTracking: 'ਆਰਡਰ ਟਰੈਕ ਕਰੋ',
    reviews: 'ਸਮੀਖਿਆਵਾਂ',
    verifiedArtisan: 'ਤਸਦੀਕਸ਼ੁਦਾ ਕਾਰੀਗਰ',
    handcrafted: '100% ਹੱਥ ਨਾਲ ਬਣਿਆ',
    offlineNotice: 'ਤੁਸੀਂ ਆਫਲਾਈਨ ਹੋ। ਤਬਦੀਲੀਆਂ ਆਪਣੇ ਆਪ ਸਿੰਕ ਹੋਣਗੀਆਂ।',
    syncPending: 'ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...',
    synced: 'ਸਭ ਕੁਝ ਸੁਰੱਖਿਅਤ ਹੈ',
    saveDraft: 'ਡਰਾਫਟ ਸੰਭਾਲੋ',
    publishProduct: 'ਮਾਰਕੀਟਪਲੇਸ ਵਿੱਚ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    priceBreakdown: 'ਕੀਮਤ ਵੇਰਵਾ',
    materialsCost: 'ਕੱਚੇ ਮਾਲ ਦੀ ਲਾਗਤ',
    labourTime: 'ਮਿਹਨਤ ਅਤੇ ਸਮਾਂ',
    suggestedPrice: 'ਸੁਝਾਈ ਗਈ ਵਿਕਰੀ ਕੀਮਤ',
    orders: 'ਆਰਡਰ',
    insights: 'ਜਾਣਕਾਰੀ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    explore: 'ਖੋਜ ਕਰੋ',
    cart: 'ਕਾਰਟ',
    wishlist: 'ਇੱਛਾ ਸੂਚੀ',
    filter: 'ਫਿਲਟਰ',
    allCrafts: 'ਸਾਰੀਆਂ ਦਸਤਕਾਰੀਆਂ',
    selectLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    continue: 'ਜਾਰੀ ਰੱਖੋ',
    skip: 'ਛੱਡੋ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
  },

  bn: {
    appName: 'কারভিয়া',
    tagline: 'কারুশিল্প। ঐতিহ্য। সংযোগ।',
    roleArtisan: 'কারিগর',
    roleBuyer: 'ক্রেতা',
    roleAdmin: 'অ্যাডমিন',
    welcomeBack: 'স্বাগতম',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    searchPlaceholder: 'হস্তশিল্প, কারিগর খুঁজুন...',
    addMyCraft: 'নতুন পণ্য যোগ করুন',
    voiceAssistant: 'কারভিয়া ভয়েস AI',
    voicePrompt: 'মাইক স্পর্শ করুন এবং আপনার ভাষায় বলুন...',
    tellKarvia: 'কারভিয়াকে বলুন আপনার কী প্রয়োজন...',
    smartCatalog: 'AI স্মার্ট ক্যাটালগ',
    craftEvidence: 'কারুশিল্প প্রমাণ প্রোফাইল',
    fairPricing: 'ন্যায্য মূল্য সহায়ক',
    trendFusion: 'ট্রেন্ড ফিউশন স্টুডিও',
    rawMaterial: 'কাঁচামালের চাহিদা তথ্য',
    schemes: 'সরকারি প্রকল্পসমূহ',
    myProducts: 'আমার পণ্যসমূহ',
    activeOrders: 'সক্রিয় অর্ডার',
    totalEarnings: 'মোট আয়',
    marketOpportunities: 'বাজারের সুযোগ',
    viewIn3D: '3D-তে দেখুন',
    virtualTryOn: 'ভার্চুয়াল ট্রাই-অন',
    visualizeInSpace: 'নিজের জায়গায় রেখে দেখুন',
    addToCart: 'কার্টে যোগ করুন',
    buyNow: 'এখনই কিনুন',
    checkout: 'চেকআউট করুন',
    orderTracking: 'অর্ডার ট্র্যাক করুন',
    reviews: 'পর্যালোচনা',
    verifiedArtisan: 'যাচাইকৃত কারিগর',
    handcrafted: '১০০% হস্তনির্মিত',
    offlineNotice: 'আপনি অফলাইনে আছেন। স্বয়ংক্রিয়ভাবে সিঙ্ক হবে।',
    syncPending: 'সিঙ্ক হচ্ছে...',
    synced: 'সব পরিবর্তন সংরক্ষিত হয়েছে',
    saveDraft: 'খসড়া সংরক্ষণ করুন',
    publishProduct: 'মার্কেটপ্লেসে প্রকাশ করুন',
    priceBreakdown: 'মূল্য বিবরণ',
    materialsCost: 'কাঁচামালের খরচ',
    labourTime: 'শ্রম ও কারুশিল্পের সময়',
    suggestedPrice: 'প্রস্তাবিত বিক্রয় মূল্য',
    orders: 'অর্ডার',
    insights: 'অন্তর্দৃষ্টি',
    profile: 'প্রোফাইল',
    explore: 'অন্বেষণ',
    cart: 'কার্ট',
    wishlist: 'পছন্দের তালিকা',
    filter: 'ফিল্টার',
    allCrafts: 'সব কারুশিল্প',
    selectLanguage: 'আপনার ভাষা নির্বাচন করুন',
    continue: 'চালিয়ে যান',
    skip: 'এড়িয়ে যান',
    getStarted: 'শুরু করুন',
  },

  mr: {
    appName: 'कार्व्हिया',
    tagline: 'हस्तकला। संस्कृती। जोडलेले।',
    roleArtisan: 'कारागीर',
    roleBuyer: 'ग्राहक',
    roleAdmin: 'प्रशासक',
    welcomeBack: 'पुन्हा स्वागत आहे',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    searchPlaceholder: 'हस्तकला, कारागीर शोधा...',
    addMyCraft: 'नवीन उत्पादन जोडा',
    voiceAssistant: 'कार्व्हिया व्हॉइस AI',
    voicePrompt: 'माईक दाबा आणि आपल्या भाषेत बोला...',
    tellKarvia: 'कार्व्हियाला सांगा तुम्हाला काय हवे आहे...',
    smartCatalog: 'AI स्मार्ट कॅटलॉग',
    craftEvidence: 'हस्तकला पुरावा प्रोफाइल',
    fairPricing: 'योग्य दर सहाय्यक',
    trendFusion: 'ट्रेंड फ्यूजन स्टुडिओ',
    rawMaterial: 'कच्च्या मालाची मागणी माहिती',
    schemes: 'शासकीय योजना',
    myProducts: 'माझी उत्पादने',
    activeOrders: 'सक्रिय ऑर्डर्स',
    totalEarnings: 'एकूण कमाई',
    marketOpportunities: 'बाजारातील संधी',
    viewIn3D: '3D मध्ये पहा',
    virtualTryOn: 'व्हर्च्युअल ट्राय-ऑन',
    visualizeInSpace: 'आपल्या जागेत ठेवून पहा',
    addToCart: 'कार्टमध्ये जोडा',
    buyNow: 'आत्ताच खरेदी करा',
    checkout: 'पैसे भरण्यासाठी पुढे जा',
    orderTracking: 'ऑर्डर ट्रॅक करा',
    reviews: 'अभिप्राय',
    verifiedArtisan: 'प्रमाणित कारागीर',
    handcrafted: '१००% हस्तनिर्मित',
    offlineNotice: 'तुम्ही ऑफलाइन आहात. आपोआप सिंक होईल.',
    syncPending: 'सिंक होत आहे...',
    synced: 'सर्व बदल सेव्ह केले आहेत',
    saveDraft: 'मसुदा सेव्ह करा',
    publishProduct: 'मार्केटप्लेसवर प्रकाशित करा',
    priceBreakdown: 'किंमत तपशील',
    materialsCost: 'कच्च्या मालाचा खर्च',
    labourTime: 'मेहनत आणि वेळ',
    suggestedPrice: 'सुचवलेली विक्री किंमत',
    orders: 'ऑर्डर्स',
    insights: 'माहिती',
    profile: 'प्रोफाइल',
    explore: 'शोधा',
    cart: 'कार्ट',
    wishlist: 'आवडती यादी',
    filter: 'फिल्टर',
    allCrafts: 'सर्व हस्तकला',
    selectLanguage: 'तुमची भाषा निवडा',
    continue: 'पुढे जा',
    skip: 'वगळा',
    getStarted: 'सुरू करा',
  },

  gu: {
    appName: 'કાર્વિયા',
    tagline: 'હસ્તકલા. સંસ્કૃતિ. જોડાણ.',
    roleArtisan: 'કારીગર',
    roleBuyer: 'ગ્રાહક',
    roleAdmin: 'એડમિન',
    welcomeBack: 'સ્વાગત છે',
    goodMorning: 'શુભ સવાર',
    goodAfternoon: 'શુભ બપોર',
    goodEvening: 'શુભ સાંજ',
    searchPlaceholder: 'હસ્તકલા, કારીગરો શોધો...',
    addMyCraft: 'નવું ઉત્પાદન ઉમેરો',
    voiceAssistant: 'કાર્વિયા વૉઇસ AI',
    voicePrompt: 'માઇક દબાવો અને તમારી ભાષામાં બોલો...',
    tellKarvia: 'કાર્વિયાને કહો તમને શું જોઈએ છે...',
    smartCatalog: 'AI સ્માર્ટ કેટલોગ',
    craftEvidence: 'હસ્તકલા પુરાવા પ્રોફાઇલ',
    fairPricing: 'વાજબી ભાવ સહાયક',
    trendFusion: 'ટ્રેન્ડ ફ્યુઝન સ્ટુડિયો',
    rawMaterial: 'કાચા માલની માંગ માહિતી',
    schemes: 'સરકારી યોજનાઓ',
    myProducts: 'મારા ઉત્પાદનો',
    activeOrders: 'ચાલુ ઓર્ડર',
    totalEarnings: 'કુલ કમાણી',
    marketOpportunities: 'બજારની તકો',
    viewIn3D: '3D માં જુઓ',
    virtualTryOn: 'વર્ચ્યુઅલ ટ્રાય-ઓન',
    visualizeInSpace: 'તમારી જગ્યામાં મૂકીને જુઓ',
    addToCart: 'કાર્ટમાં ઉમેરો',
    buyNow: 'હમણાં ખરીદો',
    checkout: 'ચેકઆઉટ કરો',
    orderTracking: 'ઓર્ડર ટ્રેક કરો',
    reviews: 'સમીક્ષાઓ',
    verifiedArtisan: 'પ્રમાણિત કારીગર',
    handcrafted: '૧૦૦% હાથથી બનાવેલ',
    offlineNotice: 'તમે ઑફલાઇન છો. આપમેળે સિંક થશે.',
    syncPending: 'સિંક થઈ રહ્યું છે...',
    synced: 'બધા ફેરફારો સાચવાયા છે',
    saveDraft: 'ડ્રાફ્ટ સાચવો',
    publishProduct: 'માર્કેટપ્લેસ પર પ્રકાશિત કરો',
    priceBreakdown: 'કિંમત વિગતો',
    materialsCost: 'કાચા માલનો ખર્ચ',
    labourTime: 'મહેનત અને સમય',
    suggestedPrice: 'સૂચવેલ વેચાણ કિંમત',
    orders: 'ઓર્ડર',
    insights: 'માહિતી',
    profile: 'પ્રોફાઇલ',
    explore: 'અન્વેષણ',
    cart: 'કાર્ટ',
    wishlist: 'પસંદગી યાદી',
    filter: 'ફિલ્ટર',
    allCrafts: 'બધી હસ્તકલા',
    selectLanguage: 'તમારી ભાષા પસંદ કરો',
    continue: 'ચાલુ રાખો',
    skip: 'છોડો',
    getStarted: 'શરૂ કરો',
  },

  or: {
    appName: 'କାର୍ଭିୟା',
    tagline: 'ହସ୍ତଶିଳ୍ପ। ସଂସ୍କୃତି। ସଂଯୋଗ।',
    roleArtisan: 'କାରିଗର',
    roleBuyer: 'ଗ୍ରାହକ',
    roleAdmin: 'ଆଡମିନ',
    welcomeBack: 'ସ୍ଵାଗତ',
    goodMorning: 'ଶୁଭ ସକାଳ',
    goodAfternoon: 'ଶୁଭ ମଧ୍ୟାହ୍ନ',
    goodEvening: 'ଶୁଭ ସନ୍ଧ୍ୟା',
    searchPlaceholder: 'ହସ୍ତଶିଳ୍ପ, କାରିଗର ଖୋଜନ୍ତୁ...',
    addMyCraft: 'ନୂତନ ଉତ୍ପାଦ ଯୋଡନ୍ତୁ',
    voiceAssistant: 'କାର୍ଭିୟା ଭଏਸ AI',
    voicePrompt: 'ମାଇକ ଦବାନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ...',
    tellKarvia: 'କାର୍ଭିୟାକୁ କୁହନ୍ତୁ ଆପଣଙ୍କୁ କଣ ଦରକାର...',
    smartCatalog: 'AI ସ୍ମାର୍ଟ କ୍ୟାଟାଲଗ୍',
    craftEvidence: 'ହସ୍ତଶିଳ୍ପ ପ୍ରମାଣ ପ୍ରୋଫାଇଲ୍',
    fairPricing: 'ଉଚିତ୍ ମୂଲ୍ୟ ସହାୟକ',
    trendFusion: 'ଟ୍ରେଣ୍ଡ ଫ୍ୟୁଜନ୍',
    rawMaterial: 'କଞ୍ଚାମାଲ ଚାହିଦା ତଥ୍ୟ',
    schemes: 'ସରକାରୀ ଯୋଜନା',
    myProducts: 'ମୋର ଉତ୍ପାଦ',
    activeOrders: 'ସକ୍ରିୟ ଅର୍ଡର',
    totalEarnings: 'ମୋଟ ରୋଜଗାର',
    marketOpportunities: 'ବଜାର ସୁଯୋଗ',
    viewIn3D: '3D ରେ ଦେଖନ୍ତୁ',
    virtualTryOn: 'ଭର୍ଚୁଆଲ୍ ଟ୍ରାଏ-ଅନ୍',
    visualizeInSpace: 'ନିଜ ସ୍ଥାନରେ ରଖି ଦେଖନ୍ତୁ',
    addToCart: 'କାର୍ଟରେ ଯୋଡନ୍ତୁ',
    buyNow: 'ବର୍ତ୍ତମାନ କିଣନ୍ତୁ',
    checkout: 'ଚେକ୍ ଆଉଟ୍ କରନ୍ତୁ',
    orderTracking: 'ଅର୍ଡର ଟ୍ରାକ୍ କରନ୍ତୁ',
    reviews: 'ସମୀକ୍ଷା',
    verifiedArtisan: 'ଯାଞ୍ଚ ହୋଇଥିବା କାରିଗର',
    handcrafted: '୧୦୦% ହସ୍ତନିର୍ମିତ',
    offlineNotice: 'ଆପଣ ଅଫଲାଇନ୍ ଅଛନ୍ତି। ସ୍ଵୟଂଚାଳିତ ଭାବେ ସିଙ୍କ ହେବ।',
    syncPending: 'ସିଙ୍କ ହେଉଛି...',
    synced: 'ସବୁ ପରିବର୍ତ୍ତନ ସଂରକ୍ଷିତ ହେଲା',
    saveDraft: 'ଡ୍ରାଫ୍ଟ ସେଭ୍ କରନ୍ତୁ',
    publishProduct: 'ବଜାରରେ ପ୍ରକାଶ କରନ୍ତୁ',
    priceBreakdown: 'ମୂଲ୍ୟ ବିବରଣୀ',
    materialsCost: 'କଞ୍ଚାମାଲ ଖର୍ଚ୍ଚ',
    labourTime: 'ଶ୍ରମ ଓ ସମୟ',
    suggestedPrice: 'ପ୍ରସ୍ତାବିତ ବିକ୍ରୟ ମୂଲ୍ୟ',
    orders: 'ଅର୍ଡର',
    insights: 'ଅନ୍ତର୍ଦୃଷ୍ଟି',
    profile: 'ପ୍ରୋଫାଇଲ୍',
    explore: 'ଅନୁସନ୍ଧାନ',
    cart: 'କାର୍ଟ',
    wishlist: 'ଇଚ୍ଛା ତାଲିକା',
    filter: 'ଫିଲ୍ଟର୍',
    allCrafts: 'ସମସ୍ତ ହସ୍ତଶିଳ୍ପ',
    selectLanguage: 'ଆପଣଙ୍କ ଭାଷା ଚୟନ କରନ୍ତୁ',
    continue: 'ଆଗକୁ ବଢନ୍ତୁ',
    skip: 'ଛାଡିଦିଅନ୍ତୁ',
    getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
  },

  as: {
    appName: 'কাৰ্ভিয়া',
    tagline: 'হস্তশিল্প। সংস্কৃতি। সংযোগ।',
    roleArtisan: 'শিল্পী / কাৰিকৰ',
    roleBuyer: 'গ্ৰাহক',
    roleAdmin: 'এডমিন',
    welcomeBack: 'স্বাগতম',
    goodMorning: 'সুপ্ৰভাত',
    goodAfternoon: 'শুভ দুপৰীয়া',
    goodEvening: 'শুভ গধূলি',
    searchPlaceholder: 'হস্তশিল্প, কাৰিকৰ সন্ধান কৰক...',
    addMyCraft: 'নতুন সামগ্ৰী যোগ কৰক',
    voiceAssistant: 'কাৰ্ভিয়া ভইচ AI',
    voicePrompt: 'মাইক স্পৰ্শ কৰক আৰু আপোনাৰ ভাষাত কওক...',
    tellKarvia: 'কাৰ্ভিয়াক কওক আপোনাক কি প্ৰয়োজন...',
    smartCatalog: 'AI স্মাৰ্ট কেটেলগ',
    craftEvidence: 'হস্তশিল্প প্ৰমাণ প্ৰফাইল',
    fairPricing: 'ন্যায্য মূল্য সহায়ক',
    trendFusion: 'ট্ৰেণ্ড ফিউজন ষ্টুডিঅ’',
    rawMaterial: 'কেঁচা সামগ্ৰীৰ চাহিদা তথ্য',
    schemes: 'চৰকাৰী আঁচনিসমূহ',
    myProducts: 'মোৰ সামগ্ৰীসমূহ',
    activeOrders: 'সক্ৰিয় অৰ্ডাৰ',
    totalEarnings: 'মুঠ উপাৰ্জন',
    marketOpportunities: 'বজাৰৰ সুযোগ',
    viewIn3D: '3D ত চাওক',
    virtualTryOn: 'ভাৰ্চুৱেল ট্ৰাই-অন',
    visualizeInSpace: 'আপোনাৰ স্থানত ৰাখি চাওক',
    addToCart: 'কাৰ্টত যোগ কৰক',
    buyNow: 'এতিয়াই কিনক',
    checkout: 'চেকআউট কৰক',
    orderTracking: 'অৰ্ডাৰ ট্ৰেক কৰক',
    reviews: 'পৰ্যালোচনা',
    verifiedArtisan: 'প্ৰমাণিত কাৰিকৰ',
    handcrafted: '১০০% হস্তনিৰ্মিত',
    offlineNotice: 'আপুনি অফলাইনত আছে। স্বয়ংক্ৰিয়ভাৱে চিঙ্ক হ’ব।',
    syncPending: 'চিঙ্ক হৈ আছে...',
    synced: 'সকলো পৰিৱৰ্তন সংৰক্ষণ কৰা হ’ল',
    saveDraft: 'খচৰা সংৰক্ষণ কৰক',
    publishProduct: 'বজাৰত প্ৰকাশ কৰক',
    priceBreakdown: 'মূল্যৰ বিৱৰণ',
    materialsCost: 'কেঁচা সামগ্ৰীৰ খৰচ',
    labourTime: 'শ্ৰম আৰু সময়',
    suggestedPrice: 'পৰামৰ্শিত বিক্ৰী মূল্য',
    orders: 'অৰ্ডাৰসমূহ',
    insights: 'তথ্য',
    profile: 'প্ৰফাইল',
    explore: 'সন্ধান কৰক',
    cart: 'কাৰ্ট',
    wishlist: 'পছন্দৰ তালিকা',
    filter: 'ফিল্টাৰ',
    allCrafts: 'সকলো হস্তশিল্প',
    selectLanguage: 'আপোনাৰ ভাষা বাছক',
    continue: 'আগবাঢ়ক',
    skip: 'এৰি যাওক',
    getStarted: 'আৰম্ভ কৰক',
  },

  ur: {
    appName: 'کارویا',
    tagline: 'دستکاری۔ ثقافت۔ رابطہ۔',
    roleArtisan: 'دستکار',
    roleBuyer: 'خریدار',
    roleAdmin: 'ایڈمن',
    welcomeBack: 'خوش آمدید',
    goodMorning: 'صبح بخیر',
    goodAfternoon: 'دوپہر بخیر',
    goodEvening: 'شام بخیر',
    searchPlaceholder: 'دستکاری، کاریگر تلاش کریں...',
    addMyCraft: 'نئی دستکاری شامل کریں',
    voiceAssistant: 'کارویا وائس AI',
    voicePrompt: 'مائیک دبائیں اور اپنی زبان میں بولیں...',
    tellKarvia: 'کارویا کو بتائیں کہ آپ کو کیا چاہیے...',
    smartCatalog: 'AI اسمارٹ کیٹلاگ',
    craftEvidence: 'دستکاری ثبوت پروفائل',
    fairPricing: 'منصفانہ قیمت معاون',
    trendFusion: 'ٹرینڈ فیوژن اسٹوڈیو',
    rawMaterial: 'خام مال طلب معلومات',
    schemes: 'سرکاری اسکیمیں',
    myProducts: 'میری مصنوعات',
    activeOrders: 'فعال آرڈرز',
    totalEarnings: 'کل آمدنی',
    marketOpportunities: 'مارکیٹ کے مواقع',
    viewIn3D: '3D میں دیکھیں',
    virtualTryOn: 'ورچوئل ٹرائی آن',
    visualizeInSpace: 'اپنی جگہ میں رکھ کر دیکھیں',
    addToCart: 'کارٹ میں شامل کریں',
    buyNow: 'ابھی خریدیں',
    checkout: 'چیک آؤٹ کریں',
    orderTracking: 'آرڈر ٹریک کریں',
    reviews: 'تبصرے',
    verifiedArtisan: 'تصدیق شدہ دستکار',
    handcrafted: '100% دست ساختہ',
    offlineNotice: 'آپ آف لائن ہیں۔ تبدیلیاں خود بخود مطابقت پذیر ہو جائیں گی۔',
    syncPending: 'مطابقت پذیری جاری ہے...',
    synced: 'تمام تبدیلیاں محفوظ ہیں',
    saveDraft: 'ڈرافٹ محفوظ کریں',
    publishProduct: 'مارکیٹ میں شائع کریں',
    priceBreakdown: 'قیمت کی تفصیل',
    materialsCost: 'خام مال کی لاگت',
    labourTime: 'محنت اور وقت',
    suggestedPrice: 'تجویز کردہ فروخت کی قیمت',
    orders: 'آرڈرز',
    insights: 'معلومات',
    profile: 'پروفائل',
    explore: 'دریافت کریں',
    cart: 'کارٹ',
    wishlist: 'پسندیدہ فہرست',
    filter: 'فلٹر',
    allCrafts: 'تمام دستکاریاں',
    selectLanguage: 'اپنی ترجیحی زبان منتخب کریں',
    continue: 'جاری رکھیں',
    skip: 'چھوڑیں',
    getStarted: 'شروع کریں',
  },
};
